package designPatterns.gof.creational.prototype;

/**
 * The interface <code>Prototype</code> defines an interface for cloning itself.
 * 
 * @pattern Prototype (role=prototypeType)
 * 
 * @generatedBy CodePro at 12/4/07 7:02 PM
 * 
 * @author Sandeep.Maloth
 * 
 * @version $Revision$
 */
public interface Prototype {

	/**
	 * Return a copy of the object
	 * 
	 * @return Prototype a copy of the object
	 */
	public Prototype createClone();
}

/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId = com.instantiations.assist.eclipse.pattern.prototypePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.prototypePattern.prototype cloneMethod = createClone package = designPatterns.gof.creational.prototype package.sourceFolder = coreJavaExamples/src
 * prototypeInterface = Prototype prototypeList =
 */